### ISSUE TITLE
Is it possible to change the seed value of the motion via an API?

### ISSUE THREAD

**Issue by thePostFuturist** [keijiro/ProceduralMotionTrack#2]

**Comment by keijiro** [comment]
Do you mean that you want to change the value in edit mode or play mode?

**Comment by thePostFuturist** [comment]
> 
> 
> Do you mean that you want to change the value in edit mode or play mode?

Play mode, via script. 

For example, if I have multiple instances of game objects with a procedural timeline assigned, I'd like them all to move differently. Which, now that I think of it, becomes two features -- change the seed value in play mode via an API, and having it only affect that instance of the prefab.

**Comment by keijiro** [comment]
Okay. Thanks for clarification.

That's technically possible but hard to provide a good UX because Timeline doesn't offer a standard way to handle per-instance (per-director) parameters. It may require some hackish tricks.

In that case, I think it's better to use a MonoBehaviour like [this one](https://github.com/keijiro/Klak/tree/master/Assets/Klak/Motion/Runtime) and control parameters with an animation track.

**Comment by thePostFuturist** [comment]
That makes sense, and your repo you linked is perfectly apt.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
